apiVersion: v1
kind: Service
metadata:
  name: petclinic-svc-stage
  annotations:
    harness.io/stage-service: "true"
spec:
  selector:
    app: petclinic
  ports:
    - port: 80
      targetPort: 80
